import {
  defineToolcraftPerformance,
  type ToolcraftPerformanceScenario,
} from "@/toolcraft/runtime";

const fullRasterValue = { renderScale: 2, grain: 40, softness: 100 };
const fullRasterFixture = {
  kind: "custom" as const,
  loadProfile: {
    hardLimit: fullRasterValue,
    metric: "custom" as const,
    smoothTarget: fullRasterValue,
    smoothTargetRatio: 1,
    target: "renderer.webgl",
    userFacingRange: "fully-guaranteed" as const,
  },
  reason: "Native 1600x1000 output at 2x preview backing with maximum grain and softness is the heaviest useful live shader state.",
  value: fullRasterValue,
};

const motionRasterValue = { grain: 40, softness: 100 };
const motionRasterFixture = {
  kind: "custom" as const,
  loadProfile: {
    hardLimit: motionRasterValue,
    metric: "custom" as const,
    smoothTarget: motionRasterValue,
    smoothTargetRatio: 1,
    target: "renderer.webgl.motion",
    userFacingRange: "fully-guaranteed" as const,
  },
  reason: "Native 1600x1000 output with maximum grain and softness is the guaranteed live-motion workload; 2x is an optional static supersampling mode.",
  value: motionRasterValue,
};

const softnessBaselineValue = { renderScale: 2, grain: 40 };
const softnessBaselineFixture = {
  kind: "custom" as const,
  loadProfile: {
    hardLimit: softnessBaselineValue,
    metric: "custom" as const,
    smoothTarget: softnessBaselineValue,
    smoothTargetRatio: 1,
    target: "texture.softness.baseline",
    userFacingRange: "fully-guaranteed" as const,
  },
  reason: "Maximum preview resolution and grain form the independent heavy baseline for Softness drag.",
  value: softnessBaselineValue,
};

const grainBaselineValue = { renderScale: 2, softness: 100 };
const grainBaselineFixture = {
  kind: "custom" as const,
  loadProfile: {
    hardLimit: grainBaselineValue,
    metric: "custom" as const,
    smoothTarget: grainBaselineValue,
    smoothTargetRatio: 1,
    target: "texture.grain.baseline",
    userFacingRange: "fully-guaranteed" as const,
  },
  reason: "Maximum preview resolution and softness form the independent heavy baseline for Grain drag.",
  value: grainBaselineValue,
};

function responsiveSlider(id: string, controlLabel: string, target: string): ToolcraftPerformanceScenario {
  return {
    automated: true,
    automatedTestName: `${id} keeps live slider feedback responsive`,
    browser: true,
    browserTestName: `browser perf: ${id} keeps live slider feedback responsive`,
    budget: { maxFrameGapMs: 120, maxInteractionMs: 1600 },
    controlLabel,
    expectedObservable: "The real slider moves continuously and the Prism Flow canvas changes during pointer drag.",
    fixture: "Prism Flow default shader",
    id,
    interaction: "control-drag",
    target,
    workload: false,
  };
}

function workloadSlider(
  id: string,
  controlLabel: string,
  target: string,
  min: number,
  defaultValue: number,
  max: number,
  workloadFixture: typeof softnessBaselineFixture | typeof grainBaselineFixture,
): ToolcraftPerformanceScenario {
  return {
    ...responsiveSlider(id, controlLabel, target),
    budget: { maxFrameGapMs: 120, maxInteractionMs: 1800, maxLongTaskMs: 250 },
    expectedObservable: "The workload slider reaches its hard limit and updates native WebGL output live.",
    fixture: `Prism Flow ${controlLabel} at its useful maximum`,
    stress: true,
    stressFixture: {
      kind: "max-value",
      loadProfile: {
        hardLimit: max,
        metric: "custom",
        smoothTarget: max,
        smoothTargetRatio: 1,
        target,
        userFacingRange: "fully-guaranteed",
      },
      reason: `${max} is the largest useful ${controlLabel} value exposed by the app.`,
      value: max,
    },
    values: { default: defaultValue, max, min },
    workload: true,
    workloadFixture,
  };
}

function responsiveControl(id: string, controlLabel: string, target: string): ToolcraftPerformanceScenario {
  return {
    automated: true,
    automatedTestName: `${id} keeps control changes responsive`,
    browser: true,
    browserTestName: `browser perf: ${id} keeps control changes responsive`,
    budget: { maxFrameGapMs: 120, maxInteractionMs: 900 },
    controlLabel,
    expectedObservable: "The visible Toolcraft control updates the prismatic output without freezing the viewport.",
    fixture: "Prism Flow default shader",
    id,
    interaction: "control-change",
    target,
    workload: false,
  };
}

const controlScenarios: ToolcraftPerformanceScenario[] = [
  responsiveControl("prism-focus-change", "Focus", "prism.focus"),
  responsiveSlider("prism-opening-drag", "Opening", "prism.opening"),
  responsiveSlider("prism-curvature-drag", "Curvature", "prism.curvature"),
  responsiveSlider("prism-volume-drag", "Volume", "prism.volume"),
  workloadSlider("texture-softness-drag", "Softness", "texture.softness", 20, 74, 100, softnessBaselineFixture),
  responsiveSlider("texture-intensity-drag", "Intensity", "texture.intensity"),
  responsiveSlider("texture-bleed-drag", "Color bleed", "texture.bleed"),
  workloadSlider("texture-grain-drag", "Grain", "texture.grain", 0, 18, 40, grainBaselineFixture),
  responsiveControl("spectrum-cyan-change", "Cyan", "spectrum.cyan"),
  responsiveControl("spectrum-blue-change", "Blue", "spectrum.blue"),
  responsiveControl("spectrum-violet-change", "Violet", "spectrum.violet"),
  responsiveControl("spectrum-magenta-change", "Magenta", "spectrum.magenta"),
  responsiveControl("spectrum-orange-change", "Orange", "spectrum.orange"),
  responsiveControl("spectrum-yellow-change", "Yellow", "spectrum.yellow"),
  responsiveSlider("motion-drift-drag", "Drift", "motion.drift"),
  responsiveSlider("motion-breathing-drag", "Breathing", "motion.breathing"),
  responsiveSlider("motion-cycles-drag", "Loop cycles", "motion.cycles"),
  responsiveControl("include-background-change", "Include", "export.includeBackground"),
  responsiveControl("background-change", "Background", "appearance.background"),
  responsiveControl("image-format-change", "Format", "export.image.format"),
  responsiveControl("video-format-change", "Format", "export.video.format"),
];

const rendererScenarios: ToolcraftPerformanceScenario[] = [
  {
    automated: true,
    automatedTestName: "WebGL prism flow preview renders within budget",
    browser: true,
    browserTestName: "browser perf: WebGL prism flow preview renders within budget",
    budget: { maxLongTaskMs: 250, maxPreviewMs: 1800, maxRenderMs: 900 },
    expectedObservable: "The complete soft prismatic field renders at the combined native raster hard limit.",
    fixture: "Prism Flow full raster preview",
    id: "preview-render",
    interaction: "preview-render",
    stress: true,
    stressFixture: fullRasterFixture,
    target: "renderer.preview",
    values: { default: { renderScale: 2, grain: 18, softness: 74 }, max: fullRasterValue, min: { renderScale: 1, grain: 0, softness: 20 } },
    workload: true,
  },
  {
    automated: true,
    automatedTestName: "Prism flow animation frames stay within budget",
    browser: true,
    browserTestName: "browser perf: Prism flow animation frames stay within budget",
    budget: { maxFrameGapMs: 120, maxLongTaskMs: 250 },
    expectedObservable: "Shader frames advance subtle ribbon drift, breathing, and grain without stalls.",
    fixture: "Prism Flow full raster timeline playback",
    id: "animation-frame",
    interaction: "animation-frame",
    stress: true,
    stressFixture: motionRasterFixture,
    target: "timeline.playback",
    values: { default: { grain: 18, softness: 74 }, max: motionRasterValue, min: { grain: 0, softness: 20 } },
    workload: true,
  },
  {
    automated: true,
    automatedTestName: "Prism flow coalesces animation during viewport drag",
    browser: true,
    browserTestName: "browser perf: Prism flow coalesces animation during viewport drag",
    budget: { maxFrameGapMs: 120, maxInteractionMs: 2000, maxLongTaskMs: 250 },
    expectedObservable: "A real canvas drag remains responsive, preserves playback state, and resumes the current shader phase.",
    fixture: "Prism Flow full raster during canvas drag",
    id: "animation-viewport-drag",
    interaction: "animation-viewport-drag",
    stress: true,
    stressFixture: motionRasterFixture,
    target: "canvas.viewport",
    values: { default: { grain: 18, softness: 74 }, max: motionRasterValue, min: { grain: 0, softness: 20 } },
    workload: true,
  },
  {
    automated: true,
    automatedTestName: "Prism flow remains responsive during toolbar zoom stress",
    browser: true,
    browserTestName: "browser perf: Prism flow remains responsive during toolbar zoom stress",
    budget: { maxFrameGapMs: 120, maxInteractionMs: 2000, maxLongTaskMs: 250 },
    expectedObservable: "Real toolbar zoom changes viewport scale without recreating the WebGL program or shifting the focal point.",
    fixture: "Prism Flow full raster during toolbar zoom",
    id: "viewport-zoom-stress",
    interaction: "viewport-zoom-stress",
    stress: true,
    stressFixture: fullRasterFixture,
    target: "canvas.zoom",
    values: { default: { renderScale: 2, grain: 18, softness: 74 }, max: fullRasterValue, min: { renderScale: 1, grain: 0, softness: 20 } },
    workload: true,
  },
  {
    automated: true,
    automatedTestName: "Prism flow timeline playback stays responsive",
    browser: true,
    browserTestName: "browser perf: Prism flow timeline playback stays responsive",
    budget: { maxFrameGapMs: 120, maxInteractionMs: 1800, maxLongTaskMs: 250 },
    controlLabel: "Play playback",
    expectedObservable: "The real timeline Play/Pause transport advances the prismatic field.",
    fixture: "Prism Flow default playback timeline",
    id: "timeline-playback",
    interaction: "timeline-playback",
    target: "timeline.playback",
    workload: false,
  },
  {
    automated: true,
    automatedTestName: "Prism flow timeline scrub stays responsive",
    browser: true,
    browserTestName: "browser perf: Prism flow timeline scrub stays responsive",
    budget: { maxFrameGapMs: 120, maxInteractionMs: 1800, maxLongTaskMs: 250 },
    controlLabel: "Playback position",
    expectedObservable: "Dragging the playback handle changes ribbon drift and grain live.",
    fixture: "Prism Flow expanded playback timeline",
    id: "timeline-scrub",
    interaction: "timeline-scrub",
    target: "timeline.currentTimeSeconds",
    workload: false,
  },
  {
    automated: true,
    automatedTestName: "Prism flow controls keep the viewport stable",
    browser: true,
    browserTestName: "browser perf: Prism flow controls keep the viewport stable",
    budget: { maxFrameGapMs: 120 },
    expectedObservable: "Canvas zoom and offset do not jump when shader uniforms change.",
    fixture: "Prism Flow default preview and viewport",
    id: "viewport-stability",
    interaction: "viewport-stability",
    target: "canvas.viewport",
    workload: false,
  },
  {
    automated: true,
    automatedTestName: "Prism flow PNG export action completes within budget",
    browser: true,
    browserTestName: "browser perf: Prism flow PNG export action completes within budget",
    budget: { maxExportMs: 8000 },
    expectedObservable: "The sticky Export PNG action returns encoded WebGL product bytes and clears pending state.",
    fixture: "Prism Flow PNG export at default 4K",
    id: "export-copy",
    interaction: "export-copy",
    target: "panel.actions",
    workload: false,
  },
];

const imageExportScenario: ToolcraftPerformanceScenario = {
  automated: true,
  automatedTestName: "8K prism flow image export completes within budget",
  browser: true,
  browserTestName: "browser perf: 8K prism flow image export completes within budget",
  budget: { maxExportMs: 8000, maxFrameGapMs: 120, maxInteractionMs: 2000, maxLongTaskMs: 250 },
  controlLabel: "Resolution",
  expectedObservable: "The 8K image path renders the shader at an 8192 pixel long edge.",
  fixture: "Prism Flow exported at 8K",
  id: "image-export-8k",
  interaction: "control-change",
  stress: true,
  stressFixture: { kind: "max-value", loadProfile: { hardLimit: "8k", metric: "custom", smoothTarget: "8k", smoothTargetRatio: 1, target: "export.image.resolution", userFacingRange: "fully-guaranteed" }, reason: "8K is the largest still export option.", value: "8k" },
  target: "export.image.resolution",
  values: { default: "4k", max: "8k", min: "2k" },
  workload: true,
  workloadFixture: fullRasterFixture,
};

const videoExportScenario: ToolcraftPerformanceScenario = {
  automated: true,
  automatedTestName: "4K prism flow video export reports frame progress",
  browser: true,
  browserTestName: "browser perf: 4K prism flow video export reports frame progress",
  budget: { maxExportMs: 8000, maxFrameGapMs: 120, maxInteractionMs: 2000, maxLongTaskMs: 250 },
  controlLabel: "Resolution",
  expectedObservable: "The 4K video path renders even-dimension shader frames and reports progress.",
  fixture: "Prism Flow short timeline exported at 4K",
  id: "video-export-4k",
  interaction: "control-change",
  stress: true,
  stressFixture: { kind: "max-value", loadProfile: { hardLimit: "4k", metric: "custom", smoothTarget: "4k", smoothTargetRatio: 1, target: "export.video.resolution", userFacingRange: "fully-guaranteed" }, reason: "4K is the largest video export option.", value: "4k" },
  target: "export.video.resolution",
  values: { default: "current", max: "4k", min: "current" },
  workload: true,
  workloadFixture: fullRasterFixture,
};

export const appPerformance = defineToolcraftPerformance({
  browserCheckPolicy: { fallbackRunner: "playwright", fallbackWhen: ["agent-browser-unavailable", "ci"], preferredRunner: "agent-browser" },
  rendererPipeline: {
    interactionInvalidation: [
      { interaction: "control-change", invalidates: ["spectral-preview"], mustNotInvalidate: ["shader-program"], targets: ["prism.focus", "spectrum.cyan", "spectrum.blue", "spectrum.violet", "spectrum.magenta", "spectrum.orange", "spectrum.yellow", "appearance.background", "export.includeBackground"] },
      { interaction: "control-drag", invalidates: ["spectral-preview"], mustNotInvalidate: ["shader-program"], targets: ["prism.opening", "prism.curvature", "prism.volume", "texture.softness", "texture.intensity", "texture.bleed", "texture.grain", "motion.drift", "motion.breathing", "motion.cycles", "canvas.renderScale"] },
      { interaction: "control-change", invalidates: ["export-composite"], mustNotInvalidate: ["shader-program"], targets: ["export.image.format", "export.image.resolution", "export.video.format", "export.video.resolution"] },
      { interaction: "animation-frame", invalidates: ["spectral-preview"], mustNotInvalidate: ["shader-program"], targets: ["timeline.currentTimeSeconds"] },
      { interaction: "timeline-playback", invalidates: ["spectral-preview"], mustNotInvalidate: ["shader-program"], targets: ["timeline.playback"] },
      { interaction: "timeline-scrub", invalidates: ["spectral-preview"], mustNotInvalidate: ["shader-program"], targets: ["timeline.currentTimeSeconds"] },
      { interaction: "viewport-drag", invalidates: [], mustNotInvalidate: ["shader-program", "spectral-preview"], targets: ["canvas.viewport"] },
      { interaction: "viewport-zoom", invalidates: [], mustNotInvalidate: ["shader-program", "spectral-preview"], targets: ["canvas.zoom"] },
      { interaction: "export", invalidates: ["export-composite"], mustNotInvalidate: ["shader-program"], targets: ["export.image.resolution", "export.video.resolution"] },
    ],
    passes: [
      { cacheKey: ["prism-flow-vertex-shader", "prism-flow-fragment-shader"], id: "shader-program", inputs: ["prism-flow-vertex-shader", "prism-flow-fragment-shader"], invalidatedBy: ["webgl-context-restoration"], kind: "preprocess", output: "intermediate", quality: "full", runsOn: "gpu" },
      { cacheKey: ["shader-program"], id: "spectral-preview", inputs: ["shader-program", "prism", "texture", "spectrum", "motion", "appearance.background", "timeline.currentTimeSeconds", "canvas.size", "canvas.renderScale"], invalidatedBy: ["prism", "texture", "spectrum", "motion", "appearance.background", "timeline.currentTimeSeconds", "canvas.size", "canvas.renderScale"], kind: "composite", output: "preview", quality: "full", runsOn: "gpu" },
      { id: "export-composite", inputs: ["shader-program", "prism", "texture", "spectrum", "motion", "appearance.background", "timeline.currentTimeSeconds", "export"], invalidatedBy: ["export"], kind: "export", output: "export", quality: "export", runsOn: "export-only" },
    ],
  },
  rendererStrategy: "webgl",
  rendererTechnique: {
    exportRenderer: "webgl",
    fidelityRisks: ["Hard gaussian falloff can read as flat wedges; the shader uses layered cores and halos so the pinch remains sharp while outer fields stay diffused.", "Excessive additive mixing can darken or clip the pale reference; normalized spectral mixing preserves luminous white space."],
    layers: [
      { content: ["composite"], exportMode: "included", id: "background", kind: "background", primitiveCount: "low", renderer: "webgl" },
      { content: ["dense-pattern", "noise", "shader"], exportMode: "included", id: "spectral-field", kind: "product-foreground", primitiveCount: "high", renderer: "webgl", uiSelector: '[data-testid="prism-flow-canvas"]' },
      { content: ["composite", "shader"], exportMode: "composited", id: "export-composite", kind: "export-composite", primitiveCount: "high", renderer: "webgl" },
    ],
    performanceRisks: ["Native 2x preview, 8K stills, and 4K video are fill-rate and encoding workloads; WebGL programs and vertex buffers are reused while controls update uniforms only."],
    previewRenderer: "webgl",
    productRepresentation: "pixel",
    rendererStrategy: "webgl",
    rendererWorkload: "pixel-output",
    sourceRepresentation: "procedural-data",
    whyNotAlternativeStrategies: ["SVG would require many overlapping blurred filter regions and produce expensive animation invalidation.", "Canvas 2D would require CPU gradient stacks or per-pixel processing for grain and diffused spectral mixing.", "WebGPU adds availability and export complexity without improving this single-pass shader workload."],
  },
  rendererWorkload: "pixel-output",
  scenarios: [...controlScenarios, ...rendererScenarios, imageExportScenario, videoExportScenario],
  usesCustomRenderer: true,
  workloadTargets: ["texture.softness", "texture.grain", "export.image.resolution", "export.video.resolution"],
});
