import { defineToolcraft } from "@/toolcraft/runtime";

export const appSchema = defineToolcraft({
  canvas: {
    enabled: true,
    renderScale: { defaultValue: 1, enabled: true, max: 2, min: 1, step: 0.5 },
    size: { height: 1000, unit: "px", width: 1600 },
    sizing: { mode: "editable-output" },
    upload: false,
  },
  panels: {
    controls: {
      sections: [
        {
          controls: {
            focus: {
              defaultValue: { x: "0.10", y: "0.04" },
              description: "Moves the optical pinch while the color field remains attached to it.",
              label: "Focus",
              performanceReason: "Focus updates two shader uniforms without rebuilding GPU resources.",
              performanceRole: "responsiveness",
              target: "prism.focus",
              type: "vector",
            },
            opening: {
              defaultValue: 78,
              description: "Controls how widely the spectrum opens away from the focal point.",
              label: "Opening",
              max: 110,
              min: 35,
              performanceReason: "Opening updates analytic band slopes in the fragment shader.",
              performanceRole: "responsiveness",
              step: 1,
              target: "prism.opening",
              type: "slider",
              unit: "%",
            },
            curvature: {
              defaultValue: 64,
              description: "Bends the left-hand ribbons into flowing optical waves.",
              label: "Curvature",
              max: 100,
              min: 0,
              performanceReason: "Curvature updates ribbon phase math only.",
              performanceRole: "responsiveness",
              step: 1,
              target: "prism.curvature",
              type: "slider",
              unit: "%",
            },
            volume: {
              defaultValue: 82,
              description: "Expands the broad colored body while preserving the central pinch.",
              label: "Volume",
              max: 120,
              min: 35,
              performanceReason: "Volume adjusts gaussian widths in one GPU pass.",
              performanceRole: "responsiveness",
              step: 1,
              target: "prism.volume",
              type: "slider",
              unit: "%",
            },
          },
          title: "Prism Shape",
        },
        {
          controls: {
            softness: {
              defaultValue: 74,
              description: "Softens ribbon edges without lowering preview resolution.",
              label: "Softness",
              max: 100,
              min: 20,
              performanceReason: "Softness changes gaussian falloff per fragment at constant pass count.",
              performanceRole: "workload",
              step: 1,
              target: "texture.softness",
              type: "slider",
              unit: "%",
            },
            intensity: {
              defaultValue: 92,
              description: "Raises spectral saturation while preserving luminous highlights.",
              label: "Intensity",
              max: 140,
              min: 35,
              performanceReason: "Intensity is a final shader composite uniform.",
              performanceRole: "responsiveness",
              step: 1,
              target: "texture.intensity",
              type: "slider",
              unit: "%",
            },
            bleed: {
              defaultValue: 62,
              description: "Adds the pale chromatic haze visible beyond the core bands.",
              label: "Color bleed",
              max: 100,
              min: 0,
              performanceReason: "Color bleed adjusts the existing halo term without adding passes.",
              performanceRole: "responsiveness",
              step: 1,
              target: "texture.bleed",
              type: "slider",
              unit: "%",
            },
            grain: {
              defaultValue: 18,
              description: "Adds fine optical grain and subtle chromatic noise to the diffused field.",
              label: "Grain",
              max: 40,
              min: 0,
              performanceReason: "Grain adds constant-cost hash noise in the fragment shader.",
              performanceRole: "workload",
              step: 1,
              target: "texture.grain",
              type: "slider",
              unit: "%",
            },
          },
          title: "Light Texture",
        },
        {
          controls: {
            cyan: { defaultValue: "#19CBE3", label: false, performanceReason: "Color changes one shader uniform.", performanceRole: "responsiveness", target: "spectrum.cyan", type: "color" },
            blue: { defaultValue: "#2865D8", label: false, performanceReason: "Color changes one shader uniform.", performanceRole: "responsiveness", target: "spectrum.blue", type: "color" },
            violet: { defaultValue: "#8C43CE", label: false, performanceReason: "Color changes one shader uniform.", performanceRole: "responsiveness", target: "spectrum.violet", type: "color" },
            magenta: { defaultValue: "#F02A9D", label: false, performanceReason: "Color changes one shader uniform.", performanceRole: "responsiveness", target: "spectrum.magenta", type: "color" },
            orange: { defaultValue: "#FF7138", label: false, performanceReason: "Color changes one shader uniform.", performanceRole: "responsiveness", target: "spectrum.orange", type: "color" },
            yellow: { defaultValue: "#FFC94A", label: false, performanceReason: "Color changes one shader uniform.", performanceRole: "responsiveness", target: "spectrum.yellow", type: "color" },
          },
          layoutGroups: [
            { columns: 2, controls: ["cyan", "blue"], layout: "inline" },
            { columns: 2, controls: ["violet", "magenta"], layout: "inline" },
            { columns: 2, controls: ["orange", "yellow"], layout: "inline" },
          ],
          title: "Spectrum",
        },
        {
          controls: {
            drift: {
              defaultValue: 46,
              description: "Moves color energy laterally through the ribbons during playback.",
              label: "Drift",
              max: 100,
              min: 0,
              performanceReason: "Drift changes timeline phase terms at constant shader cost.",
              performanceRole: "responsiveness",
              step: 1,
              target: "motion.drift",
              type: "slider",
              unit: "%",
            },
            breathing: {
              defaultValue: 42,
              description: "Adds slow expansion and contraction around the focal point.",
              label: "Breathing",
              max: 100,
              min: 0,
              performanceReason: "Breathing updates opening and width phase terms only.",
              performanceRole: "responsiveness",
              step: 1,
              target: "motion.breathing",
              type: "slider",
              unit: "%",
            },
            cycles: {
              defaultValue: 1,
              description: "Sets complete forward optical cycles per timeline loop.",
              label: "Loop cycles",
              markerCount: 4,
              max: 4,
              min: 1,
              performanceReason: "Loop cycles changes phase speed without changing fragment work.",
              performanceRole: "responsiveness",
              step: 1,
              target: "motion.cycles",
              type: "slider",
              variant: "discrete",
            },
          },
          title: "Motion",
        },
        {
          controls: {
            includeBackground: { defaultValue: true, label: "Include", performanceReason: "Background inclusion changes preview and PNG alpha compositing.", performanceRole: "responsiveness", target: "export.includeBackground", type: "switch" },
            background: { defaultValue: "#F8F7F5", label: false, performanceReason: "Background color changes the shader composite uniform.", performanceRole: "responsiveness", target: "appearance.background", type: "color" },
          },
          layoutGroups: [{ columns: 2, controls: ["includeBackground", "background"], layout: "inline" }],
          title: "Background",
        },
        {
          controls: {
            imageFormat: { defaultValue: "png", label: "Format", options: [{ label: "PNG", value: "png" }, { label: "JPG", value: "jpg" }], performanceReason: "Image format selects the final encoder.", performanceRole: "responsiveness", target: "export.image.format", type: "select" },
            imageResolution: { defaultValue: "4k", label: "Resolution", options: [{ label: "2K", value: "2k" }, { label: "4K", value: "4k" }, { label: "8K", value: "8k" }], performanceReason: "Image resolution controls final raster pixels.", performanceRole: "workload", target: "export.image.resolution", type: "select" },
          },
          layoutGroups: [{ columns: 2, controls: ["imageFormat", "imageResolution"], layout: "inline" }],
          title: "Image Export",
        },
        {
          controls: {
            videoFormat: { defaultValue: "mp4", label: "Format", options: [{ label: "MP4", value: "mp4" }, { label: "WebM", value: "webm" }], performanceReason: "Video format selects a supported recording container.", performanceRole: "responsiveness", target: "export.video.format", type: "select" },
            videoResolution: { defaultValue: "current", label: "Resolution", options: [{ label: "Current", value: "current" }, { label: "4K", value: "4k" }], performanceReason: "Video resolution changes rendered frame pixels.", performanceRole: "workload", target: "export.video.resolution", type: "select" },
          },
          layoutGroups: [{ columns: 2, controls: ["videoFormat", "videoResolution"], layout: "inline" }],
          title: "Video Export",
        },
        {
          controls: {
            outputActions: {
              actions: [
                { icon: "upload-simple", label: "Export Video", value: "export.video" },
                { icon: "upload-simple", label: "Export PNG", value: "export.png", variant: "outline" },
              ],
              target: "panel.actions",
              type: "panelActions",
            },
          },
          title: "Export",
        },
      ],
      title: "Prism Flow",
    },
    timeline: { defaultDurationSeconds: 10, enabled: true, mode: "playback" },
  },
  persistence: {
    include: ["values", "canvas", "panels", "timeline"],
    key: "toolcraft:prism-flow:state:v1",
    storage: "localStorage",
    version: 1,
  },
  settingsTransfer: { appId: "prism-flow", enabled: "auto", fileName: "prism-flow-settings.json" },
  toolbar: { history: true, radar: true, theme: true, zoom: true },
});
